---
version: 1
formatters:
  base:
    format: '%(asctime)s (%(name)s : %(addr)s) [%(levelname).1s] %(message)s'
    datefmt: '%d/%m/%Y %H:%M:%S'
handlers:
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: base
    filename: 'debug.log'
loggers:
  web:
    level: DEBUG
    handlers: [file]
    propagate: no
...
